version: '3.4'

services:
  congestiontaxcalculator.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8080:80
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
            - sqldb
  sqldb:
    image:  mcr.microsoft.com/mssql/server:2019-latest
    ports:
    - 1433:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Data123@22